### ISSUE TITLE
Separate outline overview feature from split semantics

### ISSUE THREAD

**Issue by moe2k** [zeroseven/z7_semantilizer#1]
Idea: I really like the "outline view" feature of this extension, however I don't see the need to use the "split" semantics in my project. It would be really cool if you could introduce a configuration option which decouples the overview from the "split header fields" feature, so that it would simply work with the "default" header_layout field.

**Comment by srosskopf** [comment]
Hi! Thank you for your feedback 🙂

The intended main feature of this extension is the semantic separation of the headline markup and the styling of a headline. We would be offering to disable the main feature of the extension. I still get you though, the overview of used headlines being nice enough to be used without this. But because of my points stated above, I am afraid this will have no priority for us for the time being. 

Something else you could do to bypass this, is disabling the styling field via PageTS. This way, a modifier class will never be set and you can style your headlines the way you are used to. 

Let us know this helps you 🙂

**Comment by schliesser** [comment]
We strongly recommend you the semantic separation. You could bypass this, by disabling the styling field `[header_layout]` via PageTS. This way you can style your headlines depending on the H-Type. (You may need to migrate the values from `header_layout` to `header_type` with an sql update script.)
